AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Demo"

Resources:
  Demo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.micronaut.function.aws.proxy.MicronautLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: ./build/libs/demo-0.1-all.jar
      MemorySize: 1024
      Policies:
        - AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        ApiResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
